imx8-isi-objs := imx8-isi-core.o imx8-isi-crossbar.o imx8-isi-hw.o \
	imx8-isi-pipe.o imx8-isi-video.o

obj-$(CONFIG_VIDEO_IMX_MIPI_CSIS) += imx-mipi-csis.o
obj-$(CONFIG_VIDEO_IMX8_ISI) += imx8-isi.o

